/*
 * This source file was generated by the Gradle 'init' task
 */

#ifndef APP_H
#define APP_H

#include <string>

namespace iterator {
    class Greeter {
        public:
        void doIterations();
        long innerLoop(int limit);
    };
}

#endif
